version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: update android sdk
          command: |
            echo y | android update sdk --no-ui --all --filter tool,extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository,android-29
            echo y | android update sdk --no-ui --all --filter build-tools-29.0.2
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: unit_test
          command: |
            ./gradlew test
            ./gradlew lint test
      - run:
          name: Generate APK
          command: ./gradlew assembleDebug